### ISSUE TITLE
GUI for visual checking S wave didn't work

### ISSUE THREAD

**Issue by Wufaxing** [xumi1993/seispy#71]
**Describe the bug**
wyb@Wufatian:/mnt/c/Users/22247/Desktop/littledata/ex-prf/ex-prf$ srf rf.cfg -p
2023-11-25 16:41:04,288 [RF] INFO: Load station info from ./Data.CB.NJ2
2023-11-25 16:41:04,292 [RF] INFO: CB.NJ2, latitude: 32.052, longitude: 118.854
2023-11-25 16:41:04,292 [RF] INFO: Searching earthquakes from IRIS
2023-11-25 16:41:11,969 [RF] INFO: 204 earthquakes are found
2023-11-25 16:41:11,970 [RF] INFO: Associating SAC files with earthquakes
2023-11-25 16:41:14,509 [RF] INFO: 52 earthquakes are associated
2023-11-25 16:41:14,509 [RF] INFO: Detrend all data
2023-11-25 16:41:14,829 [RF] INFO: Filter all data from 0.03 to 1.0
2023-11-25 16:41:15,133 [RF] INFO: Calculate P arrivals and ray parameters for all data
2023-11-25 16:41:15,571 [RF] INFO: Reject data record with SNR less than 3.0
2023-11-25 16:41:15,698 [RF] INFO: 47 events left after SNR calculation
2023-11-25 16:41:15,698 [RF] INFO: Rotate P phase to ZNE->LQT
2023-11-25 16:41:15,736 [RF] INFO: Pre-pick P arrival using STA/LTA method
Traceback (most recent call last):
  File "/home/wyb/.local/bin/srf", line 8, in <module>
    sys.exit(srf())
  File "/home/wyb/.local/lib/python3.8/site-packages/seispy/scripts.py", line 216, in srf
    pjt.pick()
  File "/home/wyb/.local/lib/python3.8/site-packages/seispy/rf.py", line 464, in pick
    row['data'].phase_trigger(self.para.time_before, self.para.time_after,
  File "/home/wyb/.local/lib/python3.8/site-packages/seispy/eq.py", line 282, in phase_trigger
    tr = self.st_pick.select(channel='*Z')[0]
  File "/home/wyb/.local/lib/python3.8/site-packages/obspy/core/stream.py", line 643, in __getitem__
    return self.traces.__getitem__(index)
IndexError: list index out of range

**Comment by xumi1993** [comment]
Which version do you used?

**Comment by xumi1993** [comment]
A quick way to solve this issue is that set up `phase=S` in config file.

**Comment by Wufaxing** [comment]
my version is 1.3.4, yeah it works after I add phase=S, thanks a lot!
