### ISSUE TITLE
Time-to-depth conversion of SRF

### ISSUE THREAD

**Issue by Wufaxing** [xumi1993/seispy#74]
ls the Time-to-depth conversion of SRF available now?

**Comment by xumi1993** [comment]
Is there any errors in the S-wave time-to-depth conversion? Theoretically, Both Ps and Sp phases have the same procedure on this function.

**Comment by Wufaxing** [comment]
yes, I use LQT to calculate SRFs, when I run rf2depth ccp.cfg, it only search files with comp of R 
wyb@Wufatian:/mnt/c/Users/22247/Desktop/all_SRF/SRF_1.0$ rf2depth ccp.cfg
Traceback (most recent call last):
  File "/home/wyb/.local/bin/rf2depth", line 8, in <module>
    sys.exit(rf2depth())
  File "/home/wyb/.local/lib/python3.8/site-packages/seispy/rf2depth_makedata.py", line 182, in rf2depth
    makedata(cpara)
  File "/home/wyb/.local/lib/python3.8/site-packages/seispy/rf2depth_makedata.py", line 77, in makedata
    stadatar = RFStation(rfpath, only_r=True)
  File "/home/wyb/.local/lib/python3.8/site-packages/seispy/rfcorrect.py", line 56, in __init__
    self.read_sample(data_path)
  File "/home/wyb/.local/lib/python3.8/site-packages/seispy/rfcorrect.py", line 76, in read_sample
    raise FileNotFoundError('No such files with comp of {} in {}'.format(self.comp, data_path))
FileNotFoundError: No such files with comp of R in ./RFresult/TB01

**Comment by xumi1993** [comment]
Thanks for reporting this. I'm in holiday now, I'll debug this after back to work at January.

**Comment by JouSF-1409** [comment]
I'm developing S receiver function ccp stacking via seispy during this time and  may know this one.

This is partially due to class RFStation and it's api. It needs a sample trace to init RFStation and collect neccessary information like stla, stlo .etc. 
Unfortunately, rf2depth didn't leave space for different comp. So by default, seispy is searching xxx_Rxxx.sac file rather than xxx_Lxxx.sac.

It's a little bit awkward time point, since I am working on ccp moduel right now to add S receiver function support and it requires weeks to write, run and go through a set of test.

Here's a couple of suggestions:
1. Take a deeper look into rf2depth function
2. write a py script to do rf2depth rather than rf2depth in commnad.

**Comment by xumi1993** [comment]
Hi all
In current version, I have written an API for read L component in `RFStation` as below 
```
RFStation('path/to/SRF', prime_comp='L')
```
But this function hasn't been embedded into `rf2depth`.
