### ISSUE TITLE
More than one phase were calculated with distance of 18.761302041426234 and focal depth of 10.0

### ISSUE THREAD

**Issue by AlbertSeismo** [xumi1993/seispy#85]
**Describe the bug**
The program crashes when I am processing receiver functions, and inputs in the configuration files are well set
**Expected behavior**
One P phase?

**Error raised**
2024-04-06 17:57:14,564 [RF] INFO: Calculate P arrivals and ray parameters for all data
Traceback (most recent call last):
  File "/opt/anaconda3/envs/seispy/bin/prf", line 8, in <module>
    sys.exit(prf())

             ^^^^^
  File "/opt/anaconda3/envs/seispy/lib/python3.11/site-packages/seispy/scripts.py", line 178, in prf
    pjt.cal_phase()
  File "/opt/anaconda3/envs/seispy/lib/python3.11/site-packages/seispy/rf.py", line 436, in cal_phase
    row['data'].get_arrival(self.model, row['evdp'], row['dis'], phase=self.para.phase)
  File "/opt/anaconda3/envs/seispy/lib/python3.11/site-packages/seispy/eq.py", line 185, in get_arrival

    raise ValueError('More than one phase were calculated with distance of {} and focal depth of {}'.format(dis, evdp))
ValueError: More than one phase were calculated with distance of 18.761302041426234 and focal depth of 10.0

**Platform (please complete the following information):**
 - OS: [MacOS Ventura]
 - Version [13.1]

**Comment by xumi1993** [comment]
As the error message shown, there are more than one P phases found in this case. I think you may use seismic events with distance less than 30 degree or greater than 90 degree
